server {
    listen 8080;
    root .www/;
    index index.html;
    allowed_methods GET;
}

server {
	listen 8081;
	root .www/;
	index index.html;
	allowed_methods GET;
}


server {
	listen 8082;

	root .www/;
	index index.html;
	allowed_methods GET;
}
