server {
    listen 8081;
    listen 127.0.0.1:8082;
    server_name server1.local;
    root ./www/server1;
    index index.html;
    client_max_body_size 5MB;
    error_page 404 /404.html;

    location /images {
        root ./www/server1/assets/images;
        autoindex on;
    }

    location /upload {
        allowed_methods POST;
        upload_path ./www/server1/uploads;
    }
}

server {
    listen 8083;
    listen 127.0.0.1:8084;
    server_name server2.local;
    root ./www/server2;
    index index.html;
    client_max_body_size 10MB;
    error_page 404 /404.html;

    location /images {
        root ./www/server2/assets/images;
        autoindex on;
    }

    location /upload {
        allowed_methods POST;
        upload_path ./www/server2/uploads;
    }

    location /php {
        cgi_handler .php /usr/bin/php-cgi;
    }
}