server {
	listen 8080;
	listen 127.0.0.1:8080;
	error_page 404 /404.html;
	root .www/;
	index index.html;
	allowed_methods GET;
	client_max_body_size 10MB;

	location /images {
		root ./assets/images;
		autoindex on;
	}

	location /upload {
    	allowed_methods GET POST;
    	upload_path ./upload;
    	autoindex on;
	}

	location /old {
		return https://google.com;
	}

	location /php {
		cgi_handler .php /usr/bin/php-cgi;
	}

	location / {
		allowed_methods GET DELETE;
		root .www/;
		index index.html;
	}

}
