server {
	listen 8080;
	listen 127.0.0.1:8080;
	error_page 404 /404.html;
	root .www/;
	index index.html;
	client_max_body_size 10MB;

	location /images {
		root ./assets/images;
		autoindex on;
	}

	location /upload {
		allowed_methods POST;
		upload_path ./uploads;
	}

	location /old {
		return https://google.com;
	}

	location /php {
		cgi_handler .php /usr/bin/php-cgi;
	}

	location / {
		root .www/;
		index index.html;
	}
}
